### PR TITLE
Namespacing, Composer and PHPUnit

### PR DESCRIPTION
**Pull request by carlescliment**
Hi @shuber,

I've made this changes in order to follow the current PHP standards, may be you consider them useful:
- add namespaces
- switch to composer
- switch to phpunit

### CODE REVIEW

**Comment by garak** [comment]
:+1:

**Comment by carlescliment** [comment]
@garak unfortunately this repo seems totally unmantained :(

**Comment by shuber** [comment]
@carlescliment @garak you're right, I haven't been maintaining this repository after I found these popular alternatives which support everything this library does plus curl_multi support. I'd suggest using these well maintained libraries instead:

https://github.com/rmccue/Requests
https://github.com/jyggen/curl

**Comment by carlescliment** [comment]
@shuber thankyou very much for the links and suggestions. I'll close the pull request then.

**Pull request closed without merging**
